#include <stdio.h>
#include <string.h>
#include <stdio.h>

int main () {
#define TAPE_SIZE 65536
char mem[TAPE_SIZE] = {0};
int ptr=0;

mem[ptr]=99;mem[ptr+1]=1;mem[ptr+6]=9;mem[ptr+7]=9;
while(mem[ptr]){
  mem[ptr+2]+=mem[ptr+1];mem[ptr+3]+=mem[ptr+1];
  mem[ptr+1]=0;
  mem[ptr+1]+=mem[ptr+3];
  mem[ptr+2]+=252;mem[ptr+4]++;
  mem[ptr+3]=0;
  ptr+=2;
  while(mem[ptr]){
    mem[ptr+2]--;
    mem[ptr]=0;
  }
  ptr+=2;
  while(mem[ptr]){
    mem[ptr-2]++;
    mem[ptr]=0;
  }
  ptr-=2;
  while(mem[ptr]){
    mem[ptr]=0;
    ptr+=6;
    while(mem[ptr]){
      mem[ptr-2]--;mem[ptr-1]+=10;
      mem[ptr]=0;
    }
    mem[ptr-1]--;
    mem[ptr]+=mem[ptr-1];mem[ptr+1]+=mem[ptr-1];
    mem[ptr-1]=0;
    mem[ptr-1]+=mem[ptr];
    mem[ptr]=1;
    ptr++;
    while(mem[ptr]){
      mem[ptr-1]--;
      mem[ptr]=0;
    }
    mem[ptr-9]--;
    ptr-=7;
  }
  mem[ptr]+=mem[ptr-1];mem[ptr+1]+=mem[ptr-1];
  mem[ptr-1]=0;
  mem[ptr-1]+=mem[ptr+1];
  mem[ptr]--;mem[ptr+2]++;
  mem[ptr+1]=0;
  while(mem[ptr]){
    mem[ptr+2]--;
    mem[ptr]=0;
  }
  ptr+=2;
  while(mem[ptr]){
    mem[ptr-2]++;
    mem[ptr]=0;
  }
  mem[ptr-1]+=mem[ptr-3];mem[ptr]+=mem[ptr-3];
  mem[ptr-3]=0;
  mem[ptr-3]+=mem[ptr];
  mem[ptr-1]+=254;mem[ptr+1]++;
  mem[ptr]=0;
  ptr--;
  while(mem[ptr]){
    mem[ptr+2]--;
    mem[ptr]=0;
  }
  ptr+=2;
  while(mem[ptr]){
    mem[ptr-2]++;
    mem[ptr]=0;
  }
  ptr-=2;
  while(mem[ptr]){
    mem[ptr+1]++;
    mem[ptr]=0;
  }
  ptr--;
  while(mem[ptr]){
    mem[ptr+2]++;
    mem[ptr]=0;
  }
  ptr+=2;
  while(mem[ptr]){
    mem[ptr-2]++;
    mem[ptr]=0;
  }
  mem[ptr-1]+=mem[ptr-3];mem[ptr]+=mem[ptr-3];
  mem[ptr-3]=0;
  mem[ptr-3]+=mem[ptr];
  mem[ptr-1]+=252;mem[ptr+1]++;
  mem[ptr]=0;
  ptr--;
  while(mem[ptr]){
    mem[ptr+2]--;
    mem[ptr]=0;
  }
  ptr+=2;
  while(mem[ptr]){
    mem[ptr-2]++;
    mem[ptr]=0;
  }
  ptr-=2;
  while(mem[ptr]){
    mem[ptr+1]++;
    mem[ptr]=0;
  }
  ptr--;
  while(mem[ptr]){
    mem[ptr+2]++;
    mem[ptr]=0;
  }
  ptr+=2;
  while(mem[ptr]){
    mem[ptr-2]++;
    mem[ptr]=0;
  }
  ptr-=2;
  while(mem[ptr]){
    mem[ptr+3]+=8;
    mem[ptr]=0;
    mem[ptr+5]+=6*mem[ptr+3];
    mem[ptr+3]=0;
    ptr+=4;
    while(mem[ptr]){
      mem[ptr-1]+=8;
      mem[ptr]+=6*mem[ptr-1];
      mem[ptr-1]=0;
      putchar(mem[ptr]);
      mem[ptr-1]+=8;
      mem[ptr]+=250*mem[ptr-1];
      mem[ptr-1]=0;
      mem[ptr-2]+=mem[ptr];
      mem[ptr]=0;
    }
    putchar(mem[ptr+1]);
    mem[ptr-1]+=8;
    mem[ptr+1]+=250*mem[ptr-1];
    mem[ptr-1]=0;
    mem[ptr]+=mem[ptr-2];
    mem[ptr-3]+=8;
    mem[ptr-2]=0;
    mem[ptr-4]+=4*mem[ptr-3];
    mem[ptr-3]=0;
    putchar(mem[ptr-4]);
    mem[ptr-3]+=7;
    mem[ptr-2]+=9*mem[ptr-3];
    mem[ptr-2]+=3;
    mem[ptr-3]=0;
    putchar(mem[ptr-2]);
    mem[ptr-3]+=5;
    mem[ptr-2]+=9*mem[ptr-3];
    mem[ptr-3]=0;
    putchar(mem[ptr-2]);
    mem[ptr-2]+=5;
    putchar(mem[ptr-2]);
    putchar(mem[ptr-2]);
    mem[ptr-2]+=248;
    putchar(mem[ptr-2]);
    mem[ptr-2]+=249;
    putchar(mem[ptr-2]);
    mem[ptr-2]+=14;
    mem[ptr+3]+=mem[ptr];mem[ptr+4]+=mem[ptr];
    mem[ptr]=0;
    mem[ptr]+=mem[ptr+4];
    mem[ptr+5]++;
    ptr+=3;
    while(mem[ptr]){
      mem[ptr+2]--;
      mem[ptr]=0;
    }
    ptr+=2;
    while(mem[ptr]){
      mem[ptr-2]++;
      mem[ptr]=0;
    }
    mem[ptr-1]+=mem[ptr-4];mem[ptr]+=mem[ptr-4];
    mem[ptr-4]=0;
    mem[ptr-4]+=mem[ptr];
    mem[ptr-1]--;mem[ptr+1]++;
    mem[ptr]=0;
    ptr--;
    while(mem[ptr]){
      mem[ptr+2]--;
      mem[ptr]=0;
    }
    ptr+=2;
    while(mem[ptr]){
      mem[ptr-2]++;
      mem[ptr]=0;
    }
    ptr-=3;
    while(mem[ptr]){
      mem[ptr+2]++;
      mem[ptr]=0;
    }
    ptr++;
    while(mem[ptr]){
      mem[ptr+1]++;
      mem[ptr]=0;
    }
    mem[ptr+2]++;
    mem[ptr]=2;
    mem[ptr]+=255*mem[ptr+1];
    mem[ptr+1]=0;
    while(mem[ptr]){
      mem[ptr+2]--;
      mem[ptr]=0;
    }
    ptr+=2;
    while(mem[ptr]){
      mem[ptr-2]++;
      mem[ptr]=0;
    }
    mem[ptr-1]++;
    ptr-=2;
    while(mem[ptr]){
      mem[ptr+1]--;
      mem[ptr]=0;
    }
    ptr++;
    while(mem[ptr]){
      putchar(mem[ptr-7]);
      mem[ptr]=0;
    }
    putchar(mem[ptr-9]);
    mem[ptr-7]+=252;
    putchar(mem[ptr-7]);
    mem[ptr-7]+=247;
    putchar(mem[ptr-7]);
    putchar(mem[ptr-9]);
    mem[ptr-7]+=252;
    putchar(mem[ptr-7]);
    mem[ptr-7]+=3;
    putchar(mem[ptr-7]);
    putchar(mem[ptr-7]);
    mem[ptr-7]+=13;
    putchar(mem[ptr-7]);
    mem[ptr-9]=0;mem[ptr-7]=0;
    ptr-=9;
  }
  mem[ptr]+=mem[ptr-1];mem[ptr+1]+=mem[ptr-1];
  mem[ptr-1]=0;
  mem[ptr-1]+=mem[ptr+1];
  mem[ptr]--;mem[ptr+2]++;
  mem[ptr+1]=0;
  while(mem[ptr]){
    mem[ptr+2]--;
    mem[ptr]=0;
  }
  ptr+=2;
  while(mem[ptr]){
    mem[ptr-2]++;
    mem[ptr]=0;
  }
  mem[ptr-1]+=mem[ptr-3];mem[ptr]+=mem[ptr-3];
  mem[ptr-3]=0;
  mem[ptr-3]+=mem[ptr];
  mem[ptr-1]+=252;mem[ptr+1]++;
  mem[ptr]=0;
  ptr--;
  while(mem[ptr]){
    mem[ptr+2]--;
    mem[ptr]=0;
  }
  ptr+=2;
  while(mem[ptr]){
    mem[ptr-2]++;
    mem[ptr]=0;
  }
  ptr-=2;
  while(mem[ptr]){
    mem[ptr+1]++;
    mem[ptr]=0;
  }
  ptr--;
  while(mem[ptr]){
    mem[ptr+2]++;
    mem[ptr]=0;
  }
  ptr+=2;
  while(mem[ptr]){
    mem[ptr-2]++;
    mem[ptr]=0;
  }
  ptr-=2;
  while(mem[ptr]){
    mem[ptr+1]+=8;
    mem[ptr]=0;
    mem[ptr]+=4*mem[ptr+1];
    mem[ptr+1]=0;
    putchar(mem[ptr]);
    mem[ptr+1]+=10;
    mem[ptr+2]+=11*mem[ptr+1];
    mem[ptr+2]++;
    mem[ptr+1]=0;
    putchar(mem[ptr+2]);
    mem[ptr+2]--;
    putchar(mem[ptr+2]);
    putchar(mem[ptr]);
    mem[ptr+2]+=6;
    putchar(mem[ptr+2]);
    mem[ptr+2]+=244;
    putchar(mem[ptr+2]);
    mem[ptr+2]+=253;
    putchar(mem[ptr+2]);
    putchar(mem[ptr]);
    mem[ptr+1]+=6;
    mem[ptr+2]+=3*mem[ptr+1];
    mem[ptr+1]=0;
    putchar(mem[ptr+2]);
    mem[ptr+1]+=6;
    mem[ptr+2]+=252*mem[ptr+1];
    mem[ptr+2]+=2;
    mem[ptr+1]=0;
    putchar(mem[ptr+2]);
    mem[ptr+2]+=11;
    putchar(mem[ptr+2]);
    putchar(mem[ptr+2]);
    printf("\n");
    mem[ptr]=0;mem[ptr+2]=0;
  }
  mem[ptr]+=mem[ptr-1];mem[ptr+1]+=mem[ptr-1];
  mem[ptr-1]=0;
  mem[ptr-1]+=mem[ptr+1];
  mem[ptr]+=253;mem[ptr+2]++;
  mem[ptr+1]=0;
  while(mem[ptr]){
    mem[ptr+2]--;
    mem[ptr]=0;
  }
  ptr+=2;
  while(mem[ptr]){
    mem[ptr-2]++;
    mem[ptr]=0;
  }
  ptr-=2;
  while(mem[ptr]){
    printf("\n");
    mem[ptr+1]+=9;
    mem[ptr]=10;
    mem[ptr+2]+=9*mem[ptr+1];
    mem[ptr+2]+=3;
    mem[ptr+1]=0;
    putchar(mem[ptr+2]);
    mem[ptr+2]+=13;
    putchar(mem[ptr+2]);
    mem[ptr+2]+=10;
    putchar(mem[ptr+2]);
    mem[ptr+2]+=250;
    putchar(mem[ptr+2]);
    mem[ptr+1]+=8;
    mem[ptr+3]+=4*mem[ptr+1];
    mem[ptr+1]=0;
    putchar(mem[ptr+3]);
    mem[ptr+2]+=10;
    putchar(mem[ptr+2]);
    mem[ptr+2]--;
    putchar(mem[ptr+2]);
    mem[ptr+2]+=247;
    putchar(mem[ptr+2]);
    putchar(mem[ptr+3]);
    mem[ptr+2]--;
    putchar(mem[ptr+2]);
    mem[ptr+2]+=11;
    putchar(mem[ptr+2]);
    mem[ptr+2]+=8;
    putchar(mem[ptr+2]);
    mem[ptr+2]+=247;
    putchar(mem[ptr+2]);
    putchar(mem[ptr+3]);
    mem[ptr+2]+=243;
    putchar(mem[ptr+2]);
    mem[ptr+2]+=13;
    putchar(mem[ptr+2]);
    mem[ptr+2]+=246;
    putchar(mem[ptr+2]);
    putchar(mem[ptr+3]);
    mem[ptr+2]+=12;
    putchar(mem[ptr+2]);
    mem[ptr+2]+=241;
    putchar(mem[ptr+2]);
    mem[ptr+1]+=3;
    mem[ptr+2]+=6*mem[ptr+1];
    mem[ptr+1]=0;
    putchar(mem[ptr+2]);
    putchar(mem[ptr+2]);
    putchar(mem[ptr+3]);
    mem[ptr+2]+=246;
    putchar(mem[ptr+2]);
    mem[ptr+2]+=11;
    putchar(mem[ptr+2]);
    putchar(mem[ptr+3]);
    mem[ptr+1]+=3;
    mem[ptr+2]+=250*mem[ptr+1];
    mem[ptr+2]--;
    mem[ptr+1]=0;
    putchar(mem[ptr+2]);
    mem[ptr+2]+=17;
    putchar(mem[ptr+2]);
    mem[ptr+2]+=253;
    putchar(mem[ptr+2]);
    mem[ptr+2]+=6;
    putchar(mem[ptr+2]);
    mem[ptr+2]+=249;
    putchar(mem[ptr+2]);
    mem[ptr+2]+=246;
    putchar(mem[ptr+2]);
    mem[ptr+2]=0;mem[ptr+3]=0;
    putchar(mem[ptr]);
    mem[ptr]=0;
  }
  mem[ptr]+=mem[ptr-1];mem[ptr+1]+=mem[ptr-1];
  mem[ptr-1]=0;
  mem[ptr-1]+=mem[ptr+1];
  mem[ptr]+=252;mem[ptr+2]++;
  mem[ptr+1]=0;
  while(mem[ptr]){
    mem[ptr+2]--;
    mem[ptr]=0;
  }
  ptr+=2;
  while(mem[ptr]){
    mem[ptr-2]++;
    mem[ptr]=0;
  }
  ptr-=2;
  while(mem[ptr]){
    printf("\n");
    mem[ptr-1]=0;mem[ptr]=0;
  }
  mem[ptr-1]++;
  ptr-=2;
}

return 0;
}
