#include <stdio.h>
#include <string.h>
#include <stdio.h>

int main () {
#define TAPE_SIZE 65536
char mem[TAPE_SIZE] = {0};
int ptr=0;

mem[ptr+3]=1;
ptr+=3;
while(mem[ptr]){
  mem[ptr+3]++;mem[ptr+4]+=7;
  mem[ptr]=0;mem[ptr+2]=2;
  mem[ptr+3]+=4*mem[ptr+4];mem[ptr+5]+=2*mem[ptr+4];
  mem[ptr+6]++;mem[ptr+7]++;mem[ptr+8]+=5;
  mem[ptr+4]=2;
  mem[ptr+9]+=2*mem[ptr+8];mem[ptr+10]+=6*mem[ptr+8];
  mem[ptr+8]=1;
  ptr+=11;
  mem[ptr]=getchar();
  mem[ptr-1]+=2;
  ptr--;
  while(mem[ptr]){
    while(mem[ptr]){
      ptr++;
      while(mem[ptr]){
        mem[ptr]--;
        ptr+=2;
      }
      ptr--;
      while(mem[ptr]){
        ptr+=2;
      }
      mem[ptr-2]--;
      ptr-=2;
    }
    ptr--;
    while(mem[ptr]){
      ptr--;
    }
    mem[ptr-1]++;
    ptr++;
    while(mem[ptr]){
      ptr++;
    }
    ptr++;
    while(mem[ptr]){
      mem[ptr-1]++;mem[ptr]--;
      while(mem[ptr]){
        mem[ptr-1]+=mem[ptr];
        mem[ptr]=0;
        ptr++;
      }
      ptr--;
      while(mem[ptr]){
        while(mem[ptr]){
          mem[ptr]=0;
          ptr--;
        }
        mem[ptr-1]--;
        mem[ptr]=2;
        ptr--;
        while(mem[ptr]){
          mem[ptr-1]+=9;
          mem[ptr-1]+=255*mem[ptr];
          mem[ptr]=0;
          ptr+=2;
        }
        ptr+=2;
      }
    }
    ptr-=2;
  }
  ptr--;
}
ptr--;
while(mem[ptr]){
  while(mem[ptr]){
    ptr--;
  }
  ptr++;
  while(mem[ptr]){
    while(mem[ptr]){
      ptr++;
    }
    ptr+=2;
    while(mem[ptr]){
      ptr+=2;
    }
    mem[ptr]=1;
    while(mem[ptr]){
      ptr-=2;
    }
    ptr--;
    while(mem[ptr]){
      ptr--;
    }
    mem[ptr-1]++;mem[ptr+1]--;
    ptr++;
  }
  ptr++;
  while(mem[ptr]){
    ptr++;
  }
  mem[ptr]=1;
  while(mem[ptr]){
    mem[ptr]--;
    ptr+=2;
  }
  ptr-=4;
  while(mem[ptr]){
    while(mem[ptr]){
      ptr-=2;
    }
    ptr--;
    while(mem[ptr]){
      ptr--;
    }
    mem[ptr]=1;
    ptr-=2;
    while(mem[ptr]){
      mem[ptr-1]--;mem[ptr]++;mem[ptr+1]++;
      ptr--;
      while(mem[ptr]){
        mem[ptr]--;mem[ptr+1]+=254;mem[ptr+2]++;
        while(mem[ptr]){
          mem[ptr+1]++;
          mem[ptr+2]+=mem[ptr];
          mem[ptr]=0;
        }
      }
      mem[ptr]+=mem[ptr+1];
      mem[ptr+1]=0;
    }
    mem[ptr+2]+=254;
    mem[ptr]=2;
    ptr+=3;
    while(mem[ptr]){
      ptr++;
    }
    ptr+=2;
    while(mem[ptr]){
      ptr+=2;
    }
  }
  ptr-=2;
  while(mem[ptr]){
    mem[ptr+2]++;
    ptr++;
    while(mem[ptr]){
      while(mem[ptr]){
        ptr--;
      }
      ptr--;
    }
    ptr++;
    while(mem[ptr]){
      while(mem[ptr]){
        ptr-=2;
      }
      ptr--;
      while(mem[ptr]){
        ptr--;
      }
      mem[ptr]=1;
      while(mem[ptr]){
        mem[ptr-1]++;mem[ptr]--;mem[ptr+1]--;
        ptr++;
        while(mem[ptr]){
          mem[ptr-2]++;mem[ptr-1]+=2;mem[ptr]--;
          while(mem[ptr]){
            mem[ptr-1]--;
            mem[ptr-2]+=mem[ptr];
            mem[ptr]=0;
          }
        }
        mem[ptr]+=mem[ptr-1];
        mem[ptr-1]=0;
      }
      ptr++;
      while(mem[ptr]){
        ptr++;
      }
      ptr++;
    }
    ptr++;
    while(mem[ptr]){
      ptr+=2;
    }
    ptr+=2;
  }
  ptr-=2;
  while(mem[ptr]){
    mem[ptr+2]++;mem[ptr+4]++;
    ptr+=6;
  }
  ptr-=2;
  while(mem[ptr]){
    mem[ptr]--;
    ptr+=8;
  }
  ptr-=2;
  while(mem[ptr]){
    putchar(mem[ptr+1]);
    ptr+=8;
  }
  ptr-=2;
  while(mem[ptr]){
    mem[ptr+1]--;
    ptr+=6;
  }
  ptr-=2;
  while(mem[ptr]){
    ptr++;
    mem[ptr]=getchar();
    ptr+=3;
  }
  ptr-=2;
  while(mem[ptr]){
    mem[ptr+1]++;
    ptr+=2;
  }
  ptr-=2;
  while(mem[ptr]){
    mem[ptr]++;
    ptr-=2;
  }
  ptr--;
}

return 0;
}
