#include <stdio.h>
#include <string.h>
#include <stdio.h>

int main () {
#define TAPE_SIZE 65536
char mem[TAPE_SIZE] = {0};
int ptr=0;

mem[ptr+21]=1;mem[ptr+30]=255;
ptr+=21;
while(mem[ptr]){
  mem[ptr]--;
  while(mem[ptr]){
    ptr+=10;
  }
  mem[ptr]=0;
  ptr-=10;
  while(mem[ptr]){
    mem[ptr+10]+=mem[ptr];
    mem[ptr]=0;
    ptr-=10;
  }
  ptr+=10;
  mem[ptr]=getchar();
  mem[ptr]+=246;
}
ptr+=10;
while(mem[ptr]){
  mem[ptr]+=219;mem[ptr+9]--;
  ptr+=10;
}
ptr--;
while(mem[ptr]){
  mem[ptr]++;
  ptr++;
  while(mem[ptr]){
    mem[ptr+9]++;
    ptr+=10;
  }
  mem[ptr-1]--;
  ptr-=11;
}
mem[ptr]=255;
while(mem[ptr]){
  mem[ptr+1]+=48;
  putchar(mem[ptr+1]);
  mem[ptr+1]+=208;
  ptr-=10;
}
printf(": ");
mem[ptr+8]++;mem[ptr+12]+=2;
mem[ptr]=0;
ptr+=8;
while(mem[ptr]){
  mem[ptr]=0;
  ptr+=2;
  while(mem[ptr]){
    mem[ptr+4]=0;mem[ptr+5]=0;mem[ptr+6]=0;mem[ptr+7]=0;mem[ptr+8]=0;mem[ptr+9]=0;
    mem[ptr+5]+=mem[ptr+2];mem[ptr+6]+=mem[ptr+2];
    mem[ptr+2]=0;
    ptr+=10;
  }
  ptr-=10;
  while(mem[ptr]){
    mem[ptr+2]+=mem[ptr+6];
    mem[ptr+6]=0;
    ptr-=10;
  }
  ptr+=10;
  while(mem[ptr]){
    mem[ptr+4]+=mem[ptr+1];mem[ptr+6]+=mem[ptr+1];
    mem[ptr+1]=0;
    ptr+=10;
  }
  ptr-=10;
  while(mem[ptr]){
    mem[ptr+1]+=mem[ptr+6];
    mem[ptr+6]=0;
    ptr-=10;
  }
  ptr+=10;
  while(mem[ptr]){
    mem[ptr+3]=0;mem[ptr+6]=0;mem[ptr+7]=0;
    ptr+=10;
  }
  ptr-=10;
  while(mem[ptr]){
    ptr-=10;
  }
  mem[ptr+16]++;
  mem[ptr+9]=0;
  ptr+=8;
  while(mem[ptr]){
    mem[ptr]++;
  }
  mem[ptr]=1;
  while(mem[ptr]){
    mem[ptr]--;
    ptr+=2;
    while(mem[ptr]){
      mem[ptr+7]+=2*mem[ptr+6];
      mem[ptr+6]=0;
      ptr+=10;
    }
    ptr-=10;
    while(mem[ptr]){
      mem[ptr+8]=0;mem[ptr+9]=0;
      mem[ptr+8]+=2*mem[ptr+5];
      mem[ptr+5]=0;
      ptr-=10;
    }
    ptr+=10;
    while(mem[ptr]){
      ptr+=8;
      while(mem[ptr]){
        mem[ptr]--;mem[ptr+1]++;
        while(mem[ptr]){
          mem[ptr]--;mem[ptr+1]++;
          while(mem[ptr]){
            mem[ptr]--;mem[ptr+1]++;
            while(mem[ptr]){
              mem[ptr]--;mem[ptr+1]++;
              while(mem[ptr]){
                mem[ptr]--;mem[ptr+1]++;
                while(mem[ptr]){
                  mem[ptr]--;mem[ptr+1]++;
                  while(mem[ptr]){
                    mem[ptr]--;mem[ptr+1]++;
                    while(mem[ptr]){
                      mem[ptr]--;mem[ptr+1]++;
                      while(mem[ptr]){
                        mem[ptr]--;mem[ptr+1]++;
                        while(mem[ptr]){
                          mem[ptr]--;mem[ptr+1]+=247;mem[ptr+10]++;
                          mem[ptr+1]+=mem[ptr];
                          mem[ptr]=0;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      ptr+=2;
    }
    ptr-=10;
    while(mem[ptr]){
      mem[ptr+5]+=mem[ptr+9];mem[ptr+8]+=mem[ptr+9];
      mem[ptr+9]=0;
      ptr-=10;
    }
    ptr+=10;
    while(mem[ptr]){
      ptr+=7;
      while(mem[ptr]){
        mem[ptr-1]++;mem[ptr]--;
        while(mem[ptr]){
          mem[ptr-1]++;mem[ptr]--;
          while(mem[ptr]){
            mem[ptr-1]++;mem[ptr]--;
            while(mem[ptr]){
              mem[ptr-1]++;mem[ptr]--;
              while(mem[ptr]){
                mem[ptr-1]++;mem[ptr]--;
                while(mem[ptr]){
                  mem[ptr-1]++;mem[ptr]--;
                  while(mem[ptr]){
                    mem[ptr-1]++;mem[ptr]--;
                    while(mem[ptr]){
                      mem[ptr-1]++;mem[ptr]--;
                      while(mem[ptr]){
                        mem[ptr-1]++;mem[ptr]--;
                        while(mem[ptr]){
                          mem[ptr-1]+=247;mem[ptr]--;mem[ptr+10]++;
                          mem[ptr-1]+=mem[ptr];
                          mem[ptr]=0;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      ptr+=3;
    }
    ptr-=10;
    while(mem[ptr]){
      mem[ptr+7]+=mem[ptr+4];mem[ptr+9]+=mem[ptr+4];
      mem[ptr+4]=0;
      ptr-=10;
    }
    ptr+=10;
    while(mem[ptr]){
      mem[ptr+4]+=mem[ptr+7];
      mem[ptr+7]=0;
      ptr+=10;
    }
    ptr-=10;
    while(mem[ptr]){
      mem[ptr+9]+=255*mem[ptr+8];
      mem[ptr+8]=0;
      ptr+=9;
      while(mem[ptr]){
        ptr-=9;
        while(mem[ptr]){
          mem[ptr-1]=0;
          mem[ptr-1]+=mem[ptr+9];
          mem[ptr+9]=0;
          ptr-=10;
        }
        ptr+=19;
      }
      ptr-=19;
    }
    ptr+=9;
    while(mem[ptr]){
      mem[ptr]++;
      while(mem[ptr]){
        mem[ptr]++;
        while(mem[ptr]){
          mem[ptr]++;
          while(mem[ptr]){
            mem[ptr]++;
            while(mem[ptr]){
              mem[ptr]++;
              while(mem[ptr]){
                mem[ptr]++;
                while(mem[ptr]){
                  mem[ptr]++;
                  while(mem[ptr]){
                    mem[ptr]++;
                    while(mem[ptr]){
                      mem[ptr]++;
                      while(mem[ptr]){
                        mem[ptr]++;
                        while(mem[ptr]){
                          mem[ptr-1]++;
                          mem[ptr]=0;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    ptr--;
  }
  ptr+=8;
  while(mem[ptr]){
    ptr-=6;
    while(mem[ptr]){
      mem[ptr+8]=0;mem[ptr+9]=0;
      mem[ptr+7]+=mem[ptr+4];mem[ptr+8]+=mem[ptr+4];
      mem[ptr+4]=0;
      ptr+=10;
    }
    ptr-=10;
    while(mem[ptr]){
      mem[ptr+4]+=mem[ptr+8];
      mem[ptr+8]=0;
      mem[ptr+8]+=mem[ptr+5];mem[ptr+9]+=mem[ptr+5];
      mem[ptr+5]=0;
      ptr-=10;
    }
    ptr+=10;
    while(mem[ptr]){
      mem[ptr+5]+=mem[ptr+9];
      mem[ptr+9]=0;
      ptr+=10;
    }
    ptr-=10;
    while(mem[ptr]){
      mem[ptr+7]+=255*mem[ptr+8];
      mem[ptr+8]=0;
      ptr-=10;
    }
    ptr+=10;
    while(mem[ptr]){
      ptr+=7;
      while(mem[ptr]){
        mem[ptr]--;mem[ptr+1]++;
        while(mem[ptr]){
          mem[ptr]--;mem[ptr+1]++;
          while(mem[ptr]){
            mem[ptr]--;mem[ptr+1]++;
            while(mem[ptr]){
              mem[ptr]--;mem[ptr+1]++;
              while(mem[ptr]){
                mem[ptr]--;mem[ptr+1]++;
                while(mem[ptr]){
                  mem[ptr]--;mem[ptr+1]++;
                  while(mem[ptr]){
                    mem[ptr]--;mem[ptr+1]++;
                    while(mem[ptr]){
                      mem[ptr]--;mem[ptr+1]++;
                      while(mem[ptr]){
                        mem[ptr]--;mem[ptr+1]++;
                        while(mem[ptr]){
                          mem[ptr]--;mem[ptr+1]++;
                          while(mem[ptr]){
                            mem[ptr]+=10;
                            while(mem[ptr]){
                              mem[ptr]++;mem[ptr+1]--;
                            }
                            mem[ptr+10]--;
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      ptr+=3;
    }
    mem[ptr+7]++;
    ptr+=7;
    while(mem[ptr]){
      mem[ptr]=0;
      ptr-=17;
      while(mem[ptr]){
        mem[ptr+4]=0;
        mem[ptr+4]+=mem[ptr+8];
        mem[ptr+8]=0;
        mem[ptr+8]+=mem[ptr+6];
        mem[ptr+6]=0;
        ptr-=10;
      }
      ptr+=10;
      while(mem[ptr]){
        mem[ptr+6]+=mem[ptr+8];mem[ptr+9]+=mem[ptr+8];
        mem[ptr+8]=0;
        ptr+=10;
      }
      ptr-=10;
      while(mem[ptr]){
        mem[ptr+9]+=mem[ptr+3];
        mem[ptr+3]=0;
        ptr-=10;
      }
      ptr+=10;
      while(mem[ptr]){
        ptr+=9;
        while(mem[ptr]){
          mem[ptr-6]++;mem[ptr]--;
          while(mem[ptr]){
            mem[ptr-6]++;mem[ptr]--;
            while(mem[ptr]){
              mem[ptr-6]++;mem[ptr]--;
              while(mem[ptr]){
                mem[ptr-6]++;mem[ptr]--;
                while(mem[ptr]){
                  mem[ptr-6]++;mem[ptr]--;
                  while(mem[ptr]){
                    mem[ptr-6]++;mem[ptr]--;
                    while(mem[ptr]){
                      mem[ptr-6]++;mem[ptr]--;
                      while(mem[ptr]){
                        mem[ptr-6]++;mem[ptr]--;
                        while(mem[ptr]){
                          mem[ptr-6]++;mem[ptr]--;
                          while(mem[ptr]){
                            mem[ptr-6]+=247;mem[ptr]--;mem[ptr+10]++;
                            mem[ptr-6]+=mem[ptr];
                            mem[ptr]=0;
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        ptr++;
      }
      ptr+=7;
    }
    ptr-=17;
    while(mem[ptr]){
      ptr-=10;
    }
    ptr+=10;
    while(mem[ptr]){
      mem[ptr+8]=0;
      mem[ptr+7]+=mem[ptr+6];
      mem[ptr+6]=0;
      mem[ptr+8]+=mem[ptr+5];
      mem[ptr+5]=0;
      ptr+=10;
    }
    ptr-=10;
    while(mem[ptr]){
      mem[ptr]++;
      ptr+=7;
      while(mem[ptr]){
        mem[ptr-7]++;mem[ptr]--;
        while(mem[ptr]){
          mem[ptr-7]--;mem[ptr-1]++;mem[ptr]--;
          while(mem[ptr]){
            mem[ptr-7]++;mem[ptr]--;
            while(mem[ptr]){
              mem[ptr-7]--;mem[ptr-1]++;mem[ptr]--;
              while(mem[ptr]){
                mem[ptr-7]++;mem[ptr]--;
                while(mem[ptr]){
                  mem[ptr-7]--;mem[ptr-1]++;mem[ptr]--;
                  while(mem[ptr]){
                    mem[ptr-7]++;mem[ptr]--;
                    while(mem[ptr]){
                      mem[ptr-7]--;mem[ptr-1]++;mem[ptr]--;
                      mem[ptr-7]+=mem[ptr];
                      mem[ptr]=0;
                    }
                  }
                }
              }
            }
          }
        }
      }
      mem[ptr]+=mem[ptr-7];
      mem[ptr-7]=255;
      ptr-=17;
    }
    mem[ptr-4]+=mem[ptr+7];
    mem[ptr+7]=0;
    ptr+=10;
    while(mem[ptr]){
      mem[ptr-4]+=5*mem[ptr+7];
      mem[ptr+7]=0;
      ptr+=10;
    }
    ptr-=10;
    while(mem[ptr]){
      mem[ptr]++;
      ptr+=8;
      while(mem[ptr]){
        mem[ptr-8]++;mem[ptr]--;
        while(mem[ptr]){
          mem[ptr-8]--;mem[ptr-3]++;mem[ptr]--;
          while(mem[ptr]){
            mem[ptr-8]++;mem[ptr]--;
            while(mem[ptr]){
              mem[ptr-8]--;mem[ptr-3]++;mem[ptr]--;
              while(mem[ptr]){
                mem[ptr-8]++;mem[ptr]--;
                while(mem[ptr]){
                  mem[ptr-8]--;mem[ptr-3]++;mem[ptr]--;
                  while(mem[ptr]){
                    mem[ptr-8]++;mem[ptr]--;
                    while(mem[ptr]){
                      mem[ptr-8]--;mem[ptr-3]++;mem[ptr]--;
                      mem[ptr-8]+=mem[ptr];
                      mem[ptr]=0;
                    }
                  }
                }
              }
            }
          }
        }
      }
      mem[ptr]+=mem[ptr-8];
      mem[ptr-8]=255;
      ptr-=18;
    }
    mem[ptr-5]+=mem[ptr+8];
    mem[ptr+8]=0;
    ptr+=10;
    while(mem[ptr]){
      mem[ptr-5]+=5*mem[ptr+8];
      mem[ptr+8]=0;
      ptr+=10;
    }
    ptr-=10;
    while(mem[ptr]){
      ptr-=10;
    }
    ptr+=16;
  }
  ptr-=6;
  while(mem[ptr]){
    mem[ptr+7]+=mem[ptr+3];mem[ptr+8]+=mem[ptr+3];
    mem[ptr+3]=0;
    ptr+=10;
  }
  ptr-=10;
  while(mem[ptr]){
    mem[ptr+3]+=mem[ptr+7];
    mem[ptr+7]=0;
    mem[ptr+7]+=mem[ptr+2];mem[ptr+9]+=mem[ptr+2];
    mem[ptr+2]=0;
    ptr-=10;
  }
  ptr+=10;
  while(mem[ptr]){
    mem[ptr+2]+=mem[ptr+7];
    mem[ptr+7]=0;
    ptr+=10;
  }
  ptr-=10;
  while(mem[ptr]){
    mem[ptr+8]+=255*mem[ptr+9];
    mem[ptr+9]=0;
    ptr+=8;
    while(mem[ptr]){
      ptr-=8;
      while(mem[ptr]){
        mem[ptr-2]=0;
        mem[ptr-2]+=mem[ptr+8];
        mem[ptr+8]=0;
        ptr-=10;
      }
      ptr+=18;
    }
    ptr-=18;
  }
  ptr+=8;
  while(mem[ptr]){
    mem[ptr+1]--;
    while(mem[ptr]){
      mem[ptr]++;
      while(mem[ptr]){
        mem[ptr]++;
        while(mem[ptr]){
          mem[ptr]++;
          while(mem[ptr]){
            mem[ptr]++;
            while(mem[ptr]){
              mem[ptr]++;
              while(mem[ptr]){
                mem[ptr]++;
                while(mem[ptr]){
                  mem[ptr]++;
                  while(mem[ptr]){
                    mem[ptr]++;
                    while(mem[ptr]){
                      mem[ptr]++;
                      while(mem[ptr]){
                        mem[ptr+1]++;
                        mem[ptr]=0;
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  mem[ptr+1]++;
  ptr++;
  while(mem[ptr]){
    mem[ptr+3]++;
    mem[ptr-1]=1;mem[ptr]=0;
    ptr+=11;
    while(mem[ptr]){
      ptr+=10;
    }
    ptr-=10;
    while(mem[ptr]){
      ptr-=6;
      while(mem[ptr]){
        ptr-=4;
        while(mem[ptr]){
          ptr-=10;
        }
        mem[ptr+4]++;
        ptr-=6;
      }
      ptr-=4;
    }
    ptr+=20;
    while(mem[ptr]){
      ptr+=10;
    }
    ptr-=10;
    while(mem[ptr]){
      ptr-=10;
    }
    mem[ptr+4]--;
    ptr+=4;
    while(mem[ptr]){
      while(mem[ptr]){
        mem[ptr]++;
      }
      mem[ptr+8]--;
      ptr+=6;
      while(mem[ptr]){
        mem[ptr+1]=0;
        mem[ptr+1]+=mem[ptr+3];
        mem[ptr+3]=0;
        ptr+=10;
      }
      ptr-=10;
      while(mem[ptr]){
        mem[ptr]++;
        ptr+=2;
        while(mem[ptr]){
          mem[ptr+8]++;
          ptr+=10;
        }
        mem[ptr-2]--;
        ptr-=12;
      }
      mem[ptr]=255;
      while(mem[ptr]){
        mem[ptr+2]+=48;
        putchar(mem[ptr+2]);
        mem[ptr+2]+=208;
        ptr-=10;
      }
      printf(" ");
      mem[ptr]=0;
      ptr+=4;
    }
    ptr+=6;
    while(mem[ptr]){
      ptr+=2;
      while(mem[ptr]){
        mem[ptr]--;mem[ptr+5]++;
        while(mem[ptr]){
          mem[ptr]--;mem[ptr+5]++;
          while(mem[ptr]){
            mem[ptr]--;mem[ptr+5]++;
            while(mem[ptr]){
              mem[ptr]--;mem[ptr+5]++;
              while(mem[ptr]){
                mem[ptr]--;mem[ptr+5]++;
                while(mem[ptr]){
                  mem[ptr]--;mem[ptr+5]++;
                  while(mem[ptr]){
                    mem[ptr]--;mem[ptr+5]++;
                    while(mem[ptr]){
                      mem[ptr]--;mem[ptr+5]++;
                      while(mem[ptr]){
                        mem[ptr]--;mem[ptr+5]++;
                        while(mem[ptr]){
                          mem[ptr]--;mem[ptr+5]+=247;mem[ptr+10]++;
                          mem[ptr+5]+=mem[ptr];
                          mem[ptr]=0;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      ptr+=8;
    }
    ptr-=10;
    while(mem[ptr]){
      mem[ptr+2]+=mem[ptr+7];
      mem[ptr+7]=0;
      ptr-=10;
    }
    ptr+=9;
  }
  ptr--;
}
ptr+=2;
while(mem[ptr]){
  ptr+=10;
}
ptr-=10;
while(mem[ptr]){
  mem[ptr]++;
  ptr++;
  while(mem[ptr]){
    mem[ptr+9]++;
    ptr+=10;
  }
  mem[ptr-1]--;
  ptr-=11;
}
mem[ptr]=255;
while(mem[ptr]){
  mem[ptr+1]+=48;
  putchar(mem[ptr+1]);
  ptr-=10;
}
printf("\xa" "");

return 0;
}
