#include <stdio.h>
#include <string.h>
#include <stdio.h>

int main () {
#define TAPE_SIZE 65536
char mem[TAPE_SIZE] = {0};
int ptr=0;

mem[ptr]=97;mem[ptr+1]=1;
ptr++;
while(mem[ptr]){
  mem[ptr+3]+=mem[ptr-1];
  mem[ptr-1]=0;
  mem[ptr-1]+=mem[ptr+3];mem[ptr+5]+=mem[ptr+3];
  mem[ptr+2]+=4;
  mem[ptr+3]=0;
  mem[ptr+3]+=8*mem[ptr+2];
  mem[ptr+2]=0;
  putchar(mem[ptr+3]);
  mem[ptr+2]+=3;
  mem[ptr+3]=0;
  mem[ptr+3]+=3*mem[ptr+2];
  mem[ptr+3]++;
  mem[ptr+2]=0;
  ptr+=3;
  while(mem[ptr]){
    putchar(mem[ptr+2]);
    mem[ptr]--;mem[ptr+2]++;
  }
  mem[ptr-1]+=2;
  mem[ptr+2]=0;
  mem[ptr-2]+=5*mem[ptr-1];
  mem[ptr-1]=0;
  putchar(mem[ptr-2]);
  mem[ptr]+=mem[ptr-4];
  mem[ptr-4]=0;
  mem[ptr-4]+=mem[ptr];mem[ptr+2]+=mem[ptr];
  mem[ptr]=0;
  ptr-=2;
  while(mem[ptr]){
    putchar(mem[ptr+4]);
    mem[ptr+1]+=10;mem[ptr+4]++;
    ptr++;
    while(mem[ptr]){
      mem[ptr+1]+=mem[ptr-1];
      mem[ptr-1]=0;
      mem[ptr-1]+=mem[ptr+1];mem[ptr+4]+=11*mem[ptr+1];
      mem[ptr+1]=0;
      mem[ptr+1]+=mem[ptr];
      mem[ptr]=0;
      mem[ptr]+=mem[ptr+1];mem[ptr+4]+=mem[ptr+1];
      mem[ptr+1]=0;
      mem[ptr+16]+=mem[ptr+4];mem[ptr+17]+=mem[ptr+4];
      mem[ptr+4]=0;
      ptr+=16;
      while(mem[ptr]){
        mem[ptr]--;
        mem[ptr+4]+=mem[ptr];
        mem[ptr]=0;
        mem[ptr+5]+=mem[ptr+1];
        mem[ptr+1]=0;
        ptr+=4;
      }
      mem[ptr]+=mem[ptr+3];
      mem[ptr+3]=0;
      mem[ptr+2]+=mem[ptr];mem[ptr+3]+=mem[ptr];
      mem[ptr]=0;
      ptr++;
      while(mem[ptr]){
        mem[ptr]--;
        mem[ptr-3]+=mem[ptr+1];
        mem[ptr+1]=0;
        mem[ptr-4]+=mem[ptr];
        mem[ptr]=0;
        ptr-=4;
      }
      mem[ptr-1]+=9;
      mem[ptr]+=5*mem[ptr-1];
      mem[ptr-1]=0;
      mem[ptr-1]+=mem[ptr+1];
      mem[ptr+1]=0;
      mem[ptr]+=253*mem[ptr-1];
      mem[ptr-1]=0;
      putchar(mem[ptr]);
      mem[ptr-17]--;
      mem[ptr]=0;
      ptr-=17;
    }
    printf("\n");
    mem[ptr-1]--;
    mem[ptr]=0;
    ptr--;
  }
  printf(">");
  mem[ptr+3]=0;mem[ptr+4]=0;
  ptr+=3;
  mem[ptr]=getchar();
  mem[ptr]+=246;
  mem[ptr-1]+=mem[ptr];
  mem[ptr+6]++;
  mem[ptr]=0;
  ptr--;
  while(mem[ptr]){
    mem[ptr]--;mem[ptr+1]++;mem[ptr+6]++;
    mem[ptr+7]=0;
  }
  mem[ptr+1]+=10;
  ptr+=6;
  while(mem[ptr]){
    mem[ptr]=0;
    ptr-=2;
    mem[ptr]=getchar();
    mem[ptr-7]--;
    mem[ptr-4]+=mem[ptr];
    mem[ptr]=0;
    mem[ptr]+=mem[ptr-4];mem[ptr+1]+=mem[ptr-4];
    mem[ptr+1]+=246;
    mem[ptr-4]=0;
    ptr++;
    while(mem[ptr]){
      mem[ptr-8]++;
      mem[ptr-5]+=mem[ptr-9];
      mem[ptr-9]=0;
      mem[ptr-9]+=mem[ptr-5];mem[ptr-3]+=mem[ptr-5];
      mem[ptr-5]=0;
      mem[ptr-3]+=255*mem[ptr-4];
      mem[ptr-3]+=10;
      mem[ptr-4]=0;
      mem[ptr-2]+=11*mem[ptr-3];
      mem[ptr-3]=0;
      mem[ptr-5]+=mem[ptr-9];
      mem[ptr-9]=0;
      mem[ptr-9]+=mem[ptr-5];mem[ptr-3]+=mem[ptr-5];
      mem[ptr-5]=0;
      mem[ptr-3]+=255*mem[ptr-1];
      mem[ptr-3]+=10;
      mem[ptr-1]=0;
      mem[ptr-2]+=mem[ptr-3];
      mem[ptr-3]=0;
      mem[ptr+10]+=mem[ptr-2];mem[ptr+11]+=mem[ptr-2];
      mem[ptr-2]=0;
      ptr+=10;
      while(mem[ptr]){
        mem[ptr]--;
        mem[ptr+4]+=mem[ptr];
        mem[ptr]=0;
        mem[ptr+5]+=mem[ptr+1];
        mem[ptr+1]=0;
        ptr+=4;
      }
      mem[ptr]+=mem[ptr+3];
      mem[ptr+3]=1;
      mem[ptr+3]+=255*mem[ptr];
      mem[ptr]=0;
      ptr++;
      while(mem[ptr]){
        mem[ptr]--;
        mem[ptr-3]+=mem[ptr+1];
        mem[ptr+1]=0;
        mem[ptr-4]+=mem[ptr];
        mem[ptr]=0;
        ptr-=4;
      }
      ptr-=11;
      mem[ptr]=getchar();
      mem[ptr]=0;
    }
    ptr++;
  }
  ptr++;
  while(mem[ptr]){
    mem[ptr]+=10;
    mem[ptr+1]+=11*mem[ptr];mem[ptr+2]+=11*mem[ptr];
    mem[ptr]=0;
    ptr++;
    while(mem[ptr]){
      mem[ptr]--;
      mem[ptr+3]+=mem[ptr];
      mem[ptr]=0;
      mem[ptr]+=mem[ptr+3];mem[ptr+7]+=mem[ptr+3];mem[ptr+8]+=mem[ptr+3];
      mem[ptr+3]=0;
      ptr+=7;
      while(mem[ptr]){
        mem[ptr]--;
        mem[ptr+4]+=mem[ptr];
        mem[ptr]=0;
        mem[ptr+5]+=mem[ptr+1];
        mem[ptr+1]=0;
        ptr+=4;
      }
      mem[ptr]+=mem[ptr+3];
      mem[ptr+3]=0;
      mem[ptr+2]+=mem[ptr];mem[ptr+3]+=mem[ptr];
      mem[ptr]=0;
      ptr++;
      while(mem[ptr]){
        mem[ptr]--;
        mem[ptr-3]+=mem[ptr+1];
        mem[ptr+1]=0;
        mem[ptr-4]+=mem[ptr];
        mem[ptr]=0;
        ptr-=4;
      }
      mem[ptr-5]+=mem[ptr-8];
      mem[ptr-8]=0;
      mem[ptr-8]+=mem[ptr-5];mem[ptr-1]+=mem[ptr-5];mem[ptr]+=mem[ptr-5];
      mem[ptr-5]=0;
      mem[ptr-5]+=mem[ptr-7];
      mem[ptr-7]=0;
      mem[ptr-7]+=mem[ptr-5];mem[ptr-1]+=mem[ptr-5];mem[ptr]+=mem[ptr-5];
      mem[ptr-5]=0;
      ptr--;
      while(mem[ptr]){
        mem[ptr]--;
        mem[ptr+4]+=mem[ptr];
        mem[ptr]=0;
        mem[ptr+5]+=mem[ptr+1];
        mem[ptr+1]=0;
        mem[ptr+6]+=mem[ptr+2];
        mem[ptr+2]=0;
        ptr+=4;
      }
      mem[ptr+3]=0;
      mem[ptr+3]+=mem[ptr+2];
      mem[ptr+2]=0;
      ptr++;
      while(mem[ptr]){
        mem[ptr]--;
        mem[ptr-4]+=mem[ptr];
        mem[ptr]=0;
        ptr-=4;
      }
      ptr-=8;
    }
    mem[ptr-10]+=10;
    ptr-=10;
    while(mem[ptr]){
      mem[ptr+1]+=10;
      ptr++;
      while(mem[ptr]){
        mem[ptr+1]+=mem[ptr-1];
        mem[ptr-1]=0;
        mem[ptr-1]+=mem[ptr+1];mem[ptr+4]+=11*mem[ptr+1];
        mem[ptr+1]=0;
        mem[ptr+1]+=mem[ptr];
        mem[ptr]=0;
        mem[ptr]+=mem[ptr+1];mem[ptr+4]+=mem[ptr+1];
        mem[ptr+1]=0;
        mem[ptr+1]+=mem[ptr+4];
        mem[ptr+4]=0;
        mem[ptr+4]+=mem[ptr+1];mem[ptr+9]+=mem[ptr+1];
        mem[ptr+1]=0;
        mem[ptr+12]+=mem[ptr+10];
        mem[ptr+10]=0;
        mem[ptr+9]+=mem[ptr+12];mem[ptr+10]+=mem[ptr+12];
        mem[ptr+9]+=244;
        mem[ptr+12]=0;
        mem[ptr+12]+=mem[ptr+9];
        mem[ptr+9]=0;
        mem[ptr+9]+=mem[ptr+12];mem[ptr+16]+=mem[ptr+12];mem[ptr+17]+=mem[ptr+12];
        mem[ptr+12]=0;
        ptr+=16;
        while(mem[ptr]){
          mem[ptr]--;
          mem[ptr+4]+=mem[ptr];
          mem[ptr]=0;
          mem[ptr+5]+=mem[ptr+1];
          mem[ptr+1]=0;
          ptr+=4;
        }
        mem[ptr]+=mem[ptr+3];
        mem[ptr+3]=0;
        mem[ptr+2]+=mem[ptr];mem[ptr+3]+=mem[ptr];
        mem[ptr]=0;
        mem[ptr+4]+=mem[ptr+7];
        mem[ptr+7]=0;
        mem[ptr+2]+=mem[ptr+4];mem[ptr+7]+=mem[ptr+4];
        mem[ptr+4]=0;
        mem[ptr+8]+=mem[ptr+11];
        mem[ptr+11]=0;
        mem[ptr+2]+=mem[ptr+8];mem[ptr+11]+=mem[ptr+8];
        mem[ptr+8]=0;
        ptr++;
        while(mem[ptr]){
          mem[ptr]--;
          mem[ptr-3]+=mem[ptr+1];
          mem[ptr+1]=0;
          mem[ptr-4]+=mem[ptr];
          mem[ptr]=0;
          ptr-=4;
        }
        mem[ptr-6]+=mem[ptr+1];
        mem[ptr-8]+=11;
        mem[ptr+1]=0;
        mem[ptr-5]+=mem[ptr-8];
        mem[ptr-8]=0;
        mem[ptr-8]+=mem[ptr-5];mem[ptr-1]+=mem[ptr-5];mem[ptr]+=mem[ptr-5];
        mem[ptr-5]=0;
        ptr--;
        while(mem[ptr]){
          mem[ptr]--;
          mem[ptr+4]+=mem[ptr];
          mem[ptr]=0;
          mem[ptr+5]+=mem[ptr+1];
          mem[ptr+1]=0;
          ptr+=4;
        }
        mem[ptr]+=mem[ptr+3];
        mem[ptr+3]=0;
        mem[ptr+2]+=mem[ptr];mem[ptr+3]+=mem[ptr];
        mem[ptr]=0;
        mem[ptr+4]+=mem[ptr+7];
        mem[ptr+7]=0;
        mem[ptr+2]+=mem[ptr+4];mem[ptr+7]+=mem[ptr+4];
        mem[ptr+4]=0;
        mem[ptr+8]+=mem[ptr+11];
        mem[ptr+11]=0;
        mem[ptr+2]+=mem[ptr+8];mem[ptr+11]+=mem[ptr+8];
        mem[ptr+8]=0;
        ptr++;
        while(mem[ptr]){
          mem[ptr]--;
          mem[ptr-3]+=mem[ptr+1];
          mem[ptr+1]=0;
          mem[ptr-4]+=mem[ptr];
          mem[ptr]=0;
          ptr-=4;
        }
        mem[ptr-6]+=mem[ptr+1];
        mem[ptr-8]+=11;
        mem[ptr+1]=0;
        mem[ptr-1]+=mem[ptr-8];mem[ptr]+=mem[ptr-8];
        mem[ptr-8]=0;
        ptr--;
        while(mem[ptr]){
          mem[ptr]--;
          mem[ptr+4]+=mem[ptr];
          mem[ptr]=0;
          mem[ptr+5]+=mem[ptr+1];
          mem[ptr+1]=0;
          ptr+=4;
        }
        mem[ptr]+=mem[ptr+3];
        mem[ptr+3]=0;
        mem[ptr+2]+=mem[ptr];mem[ptr+3]+=mem[ptr];
        mem[ptr]=0;
        mem[ptr+4]+=mem[ptr+7];
        mem[ptr+7]=0;
        mem[ptr+2]+=mem[ptr+4];mem[ptr+7]+=mem[ptr+4];
        mem[ptr+4]=0;
        mem[ptr+8]+=mem[ptr+11];
        mem[ptr+11]=0;
        mem[ptr+2]+=mem[ptr+8];mem[ptr+11]+=mem[ptr+8];
        mem[ptr+8]=0;
        ptr++;
        while(mem[ptr]){
          mem[ptr]--;
          mem[ptr-3]+=mem[ptr+1];
          mem[ptr+1]=0;
          mem[ptr-4]+=mem[ptr];
          mem[ptr]=0;
          ptr-=4;
        }
        mem[ptr-6]+=mem[ptr+1];
        mem[ptr-6]+=252;
        mem[ptr+1]=0;
        ptr-=6;
        while(mem[ptr]){
          mem[ptr]++;mem[ptr+7]++;
          while(mem[ptr]){
            mem[ptr+7]--;
            mem[ptr]=0;
          }
          mem[ptr+5]+=mem[ptr-7];mem[ptr+6]+=mem[ptr-7];
          mem[ptr-7]=0;
          ptr+=5;
          while(mem[ptr]){
            mem[ptr]--;
            mem[ptr+4]+=mem[ptr];
            mem[ptr]=0;
            mem[ptr+5]+=mem[ptr+1];
            mem[ptr+1]=0;
            mem[ptr+6]+=mem[ptr+2];
            mem[ptr+2]=0;
            ptr+=4;
          }
          mem[ptr+3]=0;
          mem[ptr+3]+=mem[ptr+2];
          mem[ptr+2]=0;
          ptr++;
          while(mem[ptr]){
            mem[ptr]--;
            mem[ptr-4]+=mem[ptr];
            mem[ptr]=0;
            ptr-=4;
          }
          mem[ptr-6]=0;
          ptr-=6;
        }
        mem[ptr-11]--;
        mem[ptr-7]=0;
        ptr-=11;
      }
      mem[ptr-1]--;
      ptr--;
    }
    mem[ptr+11]=0;
    ptr+=9;
  }
  ptr-=10;
}

return 0;
}
